### PR TITLE
docs: remove unstable badge

### PR DESCRIPTION
**Pull request by grant**
We're using the new Go release-please for versioning. This repo is not getting many updates.

When merged, can update https://github.com/GoogleCloudPlatform/golang-samples/pull/2049.

### CODE REVIEW

**Comment by jskeet** [comment]
"Not getting many updates" isn't a guarantee of stability though. How confident are we that there *won't* be any breaking changes before we make actual stability guarantees?

Not having used these particular badges before, I'm not entirely clear on what the requirements are.

**Comment by grant** [comment]
The goal is to merge https://github.com/GoogleCloudPlatform/golang-samples/pull/2049 – a customer and DA are questioning why we still use custom structs but talk about unmarshal libraries in our docs / presentations.

**Comment by jskeet** [comment]
Basically, removing something that says "This is unstable" seems to be an indication of "This is now stable" - and I don't know whether we want to make that claim.
Personally I wouldn't have a problem with using the unmarshalling libraries in docs and presentations while still saying "These aren't GA yet". Or we _could_ just go GA with them and increment the major version when there's a breaking change... the problem is that the cost of major versions in terms of ripple effects can be pretty high, so I'd be wary of declaring GA too early.

It looks like we only have a 0.1.0 release from this repo. How about we tie "removing the unstable badge" with "releasing 1.0.0"?

**Comment by grayside** [comment]
The unstable badge emerged from a chat with me -- we don't have a definition of stability or GA for these libraries.

I don't strongly prefer the badge, I want to make sure that we:

* Identify the definition of GA and work towards meeting those requirements
* Flag they are preview libraries and do not recommend them for production use until all requirements are met

**Comment by grant** [comment]
I've created a doc talking a little bit more about this – hope it's useful. (See email)

**Pull request closed without merging**
