### PR TITLE
docs: add doc generator and gen docs

### LINKED ISSUE #17: Generate Type Index
## Expected Behavior

We generate a type index programmatically:

| Package | Struct | Description |
| ------------- | ------------- | ------------- |
| pubsubv1 | MessagePublishedData | A message that is published by publishers and consumed by subscribers. |
| auditv1 | LogEntryData | This event is triggered when a new audit log entry is written. |

## Actual Behavior

We don't have any automatic way of generating this.

### PR DESCRIPTION
**Pull request by grant**
Adds generated documentation to this repo based on our CloudEvent JSON schema catalog.

> Note: I imagine folks will use Go docs for documentation, but the README is fine here as well.

Very similar to https://github.com/googleapis/google-cloudevents-nodejs/pull/74.

Fixes https://github.com/googleapis/google-cloudevents-go/issues/17.

Please review!

### CODE REVIEW

**Review by jskeet — COMMENTED** [review]
I'm not a big fan of having all a long list of types in detail in the top-level readme. I'd prefer to either have that as a separate document, or possibly even one document per product with a separate per-product page under a `docs` directory (or published with the package). I tend to like it when I can read the *whole* of a README and know that I've got the general gist of things, then explore deeper in specific areas. If we end up with hundreds of events, this README will be huge.

Obviously I like the fact that there *are* docs, but I'd like to wait for one of the Go experts to comment on whether this is the most appropriate place for them.

**Comment by grant** [comment]
> I'm not a big fan of having all a long list of types in detail in the top-level readme. I'd prefer to either have that as a separate document, or possibly even one document per product with a separate per-product page under a `docs` directory (or published with the package). I tend to like it when I can read the _whole_ of a README and know that I've got the general gist of things, then explore deeper in specific areas. If we end up with hundreds of events, this README will be huge.
> 
> Obviously I like the fact that there _are_ docs, but I'd like to wait for one of the Go experts to comment on whether this is the most appropriate place for them.

Sounds reasonable.

What about a separate `reference.md` doc?

I think a single doc with all the types is best to make it easy to search for a section.

**Comment by jskeet** [comment]
I'd definitely be happy with a separate `reference.md` doc for now. I still think that will get unwieldy by the time we've got (say) 200 events, but I'm happier with that gradually growing larger until we can scale it than the README doing so.

**Comment by grant** [comment]
> I'd definitely be happy with a separate `reference.md` doc for now. I still think that will get unwieldy by the time we've got (say) 200 events, but I'm happier with that gradually growing larger until we can scale it than the README doing so.

I've moved the detailed reference material to a separate `reference.md` file.

I think preparing for event types beyond GCF events is premature. Full, standard documentation is in linked Godocs.

**Review by michaelawyu — APPROVED** [review]
LGTM.

**Review by jskeet — APPROVED** [review]

**Pull request merged**
